varnish:
  image: eeacms/varnish
  ports:
  - "80:6081"
  links:
  - webapp
  environment:
  - BACKENDS_PROBE_INTERVAL=3s
  - BACKENDS_PROBE_TIMEOUT=1s
  - BACKENDS_PROBE_WINDOW=3
  - BACKENDS_PROBE_THRESHOLD=2

webapp:
  image: eeacms/hello
